-- Generated by Envision Gui2Lua, VER-1, 0-18.

local Instances = {
	ScreenGui = Instance.new("ScreenGui"),
	main = Instance.new("Frame"),
	EAB_official_mark = Instance.new("ImageLabel"),
	title = Instance.new("TextLabel"),
	Execute = Instance.new("TextButton"),
	Clear = Instance.new("TextButton"),
	TextBox = Instance.new("TextBox"),
	Close = Instance.new("TextButton"),
	OpenFrame = Instance.new("Frame"),
	play = Instance.new("TextButton"),
}

Instances.ScreenGui.Name = "ScreenGui"
Instances.ScreenGui.Parent = game.Players.LocalPlayer.PlayerGuio

Instances.main.Name = "main"
Instances.main.Parent = Instances.ScreenGui
Instances.main.Size = UDim2.new(0, 458, 0, 294)
Instances.main.Visible = false
Instances.main.Position = UDim2.new(0.235565841, 0, 0.31139648, 0)
Instances.main.BackgroundColor3 = Color3.fromRGB(0, 255, 247)

Instances.EAB_official_mark.Name = "EAB official mark"
Instances.EAB_official_mark.Parent = Instances.main
Instances.EAB_official_mark.Size = UDim2.new(0, 128, 0, 80)
Instances.EAB_official_mark.Position = UDim2.new(0.716338038, 0, 0.166666687, 0)
Instances.EAB_official_mark.BorderSizePixel = 0
Instances.EAB_official_mark.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.EAB_official_mark.Image = "http://www.roblox.com/asset/?id=4956656485"

Instances.title.Name = "title"
Instances.title.Parent = Instances.main
Instances.title.Size = UDim2.new(0, 415, 0, 34)
Instances.title.BackgroundColor3 = Color3.fromRGB(0, 156, 151)
Instances.title.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.title.Text = "EAB executor"
Instances.title.TextWrapped = true
Instances.title.TextSize = 14
Instances.title.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.title.TextScaled = true

Instances.Execute.Name = "Execute"
Instances.Execute.Parent = Instances.main
Instances.Execute.Size = UDim2.new(0, 175, 0, 40)
Instances.Execute.Position = UDim2.new(0.0327510908, 0, 0.863945603, 0)
Instances.Execute.BackgroundColor3 = Color3.fromRGB(160, 255, 249)
Instances.Execute.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.Execute.Text = "Execute"
Instances.Execute.TextSize = 14
Instances.Execute.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.Clear.Name = "Clear"
Instances.Clear.Parent = Instances.main
Instances.Clear.Size = UDim2.new(0, 175, 0, 40)
Instances.Clear.Position = UDim2.new(0.524017453, 0, 0.863945603, 0)
Instances.Clear.BackgroundColor3 = Color3.fromRGB(160, 255, 249)
Instances.Clear.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.Clear.Text = "Clear"
Instances.Clear.TextSize = 14
Instances.Clear.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.TextBox.Name = "TextBox"
Instances.TextBox.Parent = Instances.main
Instances.TextBox.Size = UDim2.new(0, 314, 0, 220)
Instances.TextBox.Position = UDim2.new(0.0351153463, 0, 0.125850335, 0)
Instances.TextBox.BackgroundColor3 = Color3.fromRGB(0, 148, 143)
Instances.TextBox.CursorPosition = -1
Instances.TextBox.TextSize = 12
Instances.TextBox.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.TextBox.TextYAlignment = Enum.TextYAlignment.Top
Instances.TextBox.Text = ""
Instances.TextBox.TextWrapped = true
Instances.TextBox.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
Instances.TextBox.TextXAlignment = Enum.TextXAlignment.Left

Instances.Close.Name = "Close"
Instances.Close.Parent = Instances.main
Instances.Close.Size = UDim2.new(0, 43, 0, 35)
Instances.Close.Position = UDim2.new(0.906113565, 0, -0.00340136047, 0)
Instances.Close.BackgroundColor3 = Color3.fromRGB(0, 93, 88)
Instances.Close.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.Close.Text = "X"
Instances.Close.TextWrapped = true
Instances.Close.TextSize = 14
Instances.Close.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.Close.TextScaled = true

Instances.OpenFrame.Name = "OpenFrame"
Instances.OpenFrame.Parent = Instances.ScreenGui
Instances.OpenFrame.Size = UDim2.new(0, 100, 0, 49)
Instances.OpenFrame.Position = UDim2.new(0, 0, 0.598715901, 0)
Instances.OpenFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)

Instances.play.Name = "play"
Instances.play.Parent = Instances.OpenFrame
Instances.play.Size = UDim2.new(0, 100, 0, 50)
Instances.play.BackgroundColor3 = Color3.fromRGB(0, 93, 88)
Instances.play.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.play.Text = "CLOSE"
Instances.play.TextWrapped = true
Instances.play.TextSize = 14
Instances.play.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
Instances.play.TextScaled = true

-- Function "LocalScript"
(function()
	local script = Instance.new("LocalScript", Instances.play)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent.main.Visible = not script.Parent.Parent.Parent.main.Visible
		script.Parent.Text = not script.Parent.Parent.Parent.main.Visible and "OPEN" or script.Parent.Parent.Parent.main.Visible and "CLOSE"
	end)
end)()

-- Function "Script"
(function()
	local script = Instance.new("Script", Instances.ScreenGui)
	script.Parent.main.Execute.MouseButton1Click:Connect(function()
	    local loadstring = require(script.Loadstring)
		loadstring(script.Parent.main.TextBox.Text)()
	end)
end)()

--[[ End of generation. ]]
